#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
分析模块
========

本模块包含各种分析器组件：
- DataFlowAnalyzer: 数据流分析器
- KnowledgeBase: 知识库管理类
- RecommendationEngine: 推荐引擎
- SubskillOptimizer: 子技能优化器
"""

from .data_flow_analyzer import DataFlowAnalyzer
from .knowledge_base import (
    KnowledgeBase,
    KnowledgeItem,
    KnowledgeType,
    KnowledgeStatus,
    StorageType,
    SearchMode,
    SearchResult,
    KnowledgeVersion,
    create_fix_pattern_knowledge,
    create_best_practice_knowledge,
    create_diagnosis_knowledge,
    create_code_pattern_knowledge
)
from .recommendation_engine import (
    RecommendationEngine,
    Recommendation,
    RecommendationCategory,
    RecommendationPriority,
    RecommendationStatus,
    BestPractice,
    UserPreference,
    RecommendationFeedback,
    RecommendationEffect,
    RecommendationReport,
    BestPracticeRecommender,
    OptimizationRecommender,
    PersonalizedRecommender,
    RecommendationEffectTracker
)
from .subskill_optimizer import (
    SubskillOptimizer,
    SubskillCategory,
    QualityLevel,
    OptimizationPriority,
    UpdateType,
    DocumentStructure,
    ContentQuality,
    UsageStatistics,
    EffectEvaluation,
    SubskillAnalysis,
    OptimizationSuggestion,
    UpdatePlan,
    OptimizationReport,
    DocumentStructureAnalyzer,
    ContentQualityAnalyzer,
    EffectEvaluator,
    SuggestionGenerator,
    SubskillUpdater
)
from .knowledge_learning_system import (
    PatternRecognizer,
    BestPracticeExtractor,
    FixStrategyLearner,
    KnowledgeQualityEvaluator,
    KnowledgeLearningSystem,
    PatternCategory,
    PatternConfidence,
    CodePattern,
    BehavioralPattern,
    PatternMatchResult,
    PracticeCategory,
    PracticeLevel,
    BestPractice,
    PracticeRecommendation,
    FixStrategyType,
    FixEffectiveness,
    FixStrategy,
    FixRecord,
    StrategyEvaluation,
    QualityDimension,
    QualityLevel as KnowledgeQualityLevel,
    QualityScore,
    ValidationResult,
    RetirementCandidate
)

__all__ = [
    'DataFlowAnalyzer',
    'KnowledgeBase',
    'KnowledgeItem',
    'KnowledgeType',
    'KnowledgeStatus',
    'StorageType',
    'SearchMode',
    'SearchResult',
    'KnowledgeVersion',
    'create_fix_pattern_knowledge',
    'create_best_practice_knowledge',
    'create_diagnosis_knowledge',
    'create_code_pattern_knowledge',
    'RecommendationEngine',
    'Recommendation',
    'RecommendationCategory',
    'RecommendationPriority',
    'RecommendationStatus',
    'BestPractice',
    'UserPreference',
    'RecommendationFeedback',
    'RecommendationEffect',
    'RecommendationReport',
    'BestPracticeRecommender',
    'OptimizationRecommender',
    'PersonalizedRecommender',
    'RecommendationEffectTracker',
    'SubskillOptimizer',
    'SubskillCategory',
    'QualityLevel',
    'OptimizationPriority',
    'UpdateType',
    'DocumentStructure',
    'ContentQuality',
    'UsageStatistics',
    'EffectEvaluation',
    'SubskillAnalysis',
    'OptimizationSuggestion',
    'UpdatePlan',
    'OptimizationReport',
    'DocumentStructureAnalyzer',
    'ContentQualityAnalyzer',
    'EffectEvaluator',
    'SuggestionGenerator',
    'SubskillUpdater',
    'PatternRecognizer',
    'BestPracticeExtractor',
    'FixStrategyLearner',
    'KnowledgeQualityEvaluator',
    'KnowledgeLearningSystem',
    'PatternCategory',
    'PatternConfidence',
    'CodePattern',
    'BehavioralPattern',
    'PatternMatchResult',
    'PracticeCategory',
    'PracticeLevel',
    'BestPractice',
    'PracticeRecommendation',
    'FixStrategyType',
    'FixEffectiveness',
    'FixStrategy',
    'FixRecord',
    'StrategyEvaluation',
    'QualityDimension',
    'KnowledgeQualityLevel',
    'QualityScore',
    'ValidationResult',
    'RetirementCandidate'
]
