#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
质量监控模块

提供质量指标收集、趋势分析、门禁检查和技术债务追踪功能。
"""

from .tech_debt_tracker import (
    DebtType,
    DebtStatus,
    DebtPriority,
    DebtCategory,
    DebtItem,
    RepaymentTask,
    RepaymentPlan,
    DebtTrend,
    DebtTrackerReport,
    TechDebtTracker,
    TodoCommentDetector,
    DeprecatedAPIDetector,
    CodeSmellDetector,
    DuplicateCodeDetector,
    MissingTestDetector,
    MissingDocDetector,
    DebtStateManager,
    RepaymentPlanGenerator,
)

from .quality_metrics_collector import (
    MetricCategory,
    MetricType,
    GateStatus,
    Severity,
    MetricDefinition,
    MetricValue,
    CodeQualityMetrics,
    TestQualityMetrics,
    DocumentationQualityMetrics,
    ArchitectureQualityMetrics,
    QualityMetricsCollection,
    GateCheckResult,
    QualityGateReport,
    TrendDataPoint,
    TrendAnalysis,
    QualityMetricsRegistry,
    CodeQualityCollector,
    TestQualityCollector,
    DocumentationQualityCollector,
    ArchitectureQualityCollector,
    QualityMetricsCollector,
    QualityTrendAnalyzer,
    QualityGateChecker,
    ReportGenerator as MetricsReportGenerator,
)

__all__ = [
    "DebtType",
    "DebtStatus",
    "DebtPriority",
    "DebtCategory",
    "DebtItem",
    "RepaymentTask",
    "RepaymentPlan",
    "DebtTrend",
    "DebtTrackerReport",
    "TechDebtTracker",
    "TodoCommentDetector",
    "DeprecatedAPIDetector",
    "CodeSmellDetector",
    "DuplicateCodeDetector",
    "MissingTestDetector",
    "MissingDocDetector",
    "DebtStateManager",
    "RepaymentPlanGenerator",
    "MetricCategory",
    "MetricType",
    "GateStatus",
    "Severity",
    "MetricDefinition",
    "MetricValue",
    "CodeQualityMetrics",
    "TestQualityMetrics",
    "DocumentationQualityMetrics",
    "ArchitectureQualityMetrics",
    "QualityMetricsCollection",
    "GateCheckResult",
    "QualityGateReport",
    "TrendDataPoint",
    "TrendAnalysis",
    "QualityMetricsRegistry",
    "CodeQualityCollector",
    "TestQualityCollector",
    "DocumentationQualityCollector",
    "ArchitectureQualityCollector",
    "QualityMetricsCollector",
    "QualityTrendAnalyzer",
    "QualityGateChecker",
    "MetricsReportGenerator",
]
