from .base_adapter import (
    PlatformAdapter,
    PlatformType,
    ExecutionResult,
    EnvironmentInfo,
)

from .powershell_adapter import (
    PowerShell7Adapter,
    PowerShellExecutionResult,
    PowerShellSessionPool,
    BASH_TO_PS_COMMAND_MAP,
)

from .bash_adapter import (
    BashAdapter,
    BashExecutionResult,
    BackgroundProcess,
)

from .cross_platform_utils import (
    detect_os,
    detect_terminal,
    normalize_path,
    detect_encoding,
    convert_to_utf8_no_bom,
    get_home_directory,
    get_temp_directory,
    is_admin,
    get_env_var,
    set_env_var,
    get_platform_info,
    get_default_encoding,
    ensure_directory_exists,
    safe_filename,
    join_paths,
    relative_to,
    expand_user,
    file_size_human_readable,
    is_executable,
    which,
    check_command_available,
    run_cross_platform,
    get_adapter_for_current_platform,
)

__all__ = [
    "PlatformAdapter",
    "PlatformType",
    "ExecutionResult",
    "EnvironmentInfo",
    "PowerShell7Adapter",
    "PowerShellExecutionResult",
    "PowerShellSessionPool",
    "BASH_TO_PS_COMMAND_MAP",
    "BashAdapter",
    "BashExecutionResult",
    "BackgroundProcess",
    "detect_os",
    "detect_terminal",
    "normalize_path",
    "detect_encoding",
    "convert_to_utf8_no_bom",
    "get_home_directory",
    "get_temp_directory",
    "is_admin",
    "get_env_var",
    "set_env_var",
    "get_platform_info",
    "get_default_encoding",
    "ensure_directory_exists",
    "safe_filename",
    "join_paths",
    "relative_to",
    "expand_user",
    "file_size_human_readable",
    "is_executable",
    "which",
    "check_command_available",
    "run_cross_platform",
    "get_adapter_for_current_platform",
]
